/* Autogenerated - do not fiddle */
            if(typeof(Contracts) === "undefined") var Contracts={};
            (function(module, Contracts) {
                var data = {
                    address: "0xa9e73bb65b54c445081dae9d67f08ccbcce8bcb7",
                    network: "browser",
                    endpoint: "http://ethereum-studio-browser",
                    abi: [
    {
        "constant": true,
        "inputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "name": "leases",
        "outputs": [
            {
                "name": "landlordName",
                "type": "string"
            },
            {
                "name": "tenantName",
                "type": "string"
            },
            {
                "name": "leaseSignedDate",
                "type": "string"
            },
            {
                "name": "leaseStartDate",
                "type": "string"
            },
            {
                "name": "leaseEndDate",
                "type": "string"
            },
            {
                "name": "leaseAddress",
                "type": "string"
            },
            {
                "name": "apartmentNumber",
                "type": "uint256"
            },
            {
                "name": "leaseCost",
                "type": "uint256"
            }
        ],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
    },
    {
        "constant": false,
        "inputs": [
            {
                "name": "_landlordName",
                "type": "string"
            },
            {
                "name": "_tenantName",
                "type": "string"
            },
            {
                "name": "_leaseSignedDate",
                "type": "string"
            },
            {
                "name": "_leaseStartDate",
                "type": "string"
            },
            {
                "name": "_leaseEndDate",
                "type": "string"
            },
            {
                "name": "_leaseAddress",
                "type": "string"
            },
            {
                "name": "_apartmentNumber",
                "type": "uint256"
            },
            {
                "name": "_leaseCost",
                "type": "uint256"
            }
        ],
        "name": "createNewLease",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
    }
]
                };
                Contracts["NewLease"] = data;
                console.log(data);
                module.exports = data;
            })((typeof(module) === "undefined" ? {} : module), Contracts);